# Generated by Django 5.1.1 on 2024-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_kwh', models.FloatField(help_text='Electricity usage in kwh')),
                ('gas_kwh', models.FloatField(help_text='Gas usage in KWh')),
                ('heating_oil_liters', models.FloatField(help_text='Heating oil usage in liters')),
            ],
        ),
        migrations.CreateModel(
            name='FoodConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_per_week', models.FloatField(help_text='Meat consumption per week (kg)')),
                ('dairy_per_week', models.FloatField(help_text='Dairy consumption per week (kg)')),
                ('plant_based_per_week', models.FloatField(help_text='Plant-based food consumption per week (kg)')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_miles', models.FloatField(help_text='Distance traveled by car (miles)')),
                ('public_transport_miles', models.FloatField(help_text='Distance traveled by public transport (miles)')),
                ('flights_hours', models.FloatField(help_text='Hours spent on flights')),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_kg', models.FloatField(help_text='Amount of waste produced (kg)')),
                ('recycling_percentage', models.FloatField(help_text='Percentage of waste recycled (%)')),
            ],
        ),
    ]
